<?php


/**
 * Example of altering all the forms that are seen
 *  Edit, View, Add
 * Note:
 *  Group your code in a module based namespace eg
 *  behat_editor_example_click
 *  behat_editor_example_click_group
 *  behat_editor_example_field_text
 *
 *  The form "group" needs to be placed inside a category. In this case it is form_fields_and_elements.
 *  If you look at the behat_editor/tpl/behat_editor_shared_views.inc you will see the grouping choices.
 *
 *  Notice there is a name just to make sure it is consistant.
 *
 *  ...
 *  The Title is what is used for text as well as the values entered or chosen.
 *
 *  Finally the button has a few data elements to pass information to the javascript.
 *    class = steps for most needs
 *    data-type = select to help pass some extra info to the javascript function found in
 *       behat_editor/js/behat_editor_scenario_builder.js
 *    data-method = append for most steps replace would be if you wanted to replace the relative step
 *
 *  Review behat_editor/tpl/behat_shared_views.inc for more layout examples.
 *
 *  @param $form
 *  @param $form_state
 */
function behat_editor_example_form_alter(&$form, &$form_state) {
    $forms = array('behat-editor-edit-form', 'behat-editor-add-form');
    if(in_array($form['#id'], $forms)) {
        $form['questions_area']['question']['questions']['form_fields_and_elements']['behat_editor_example_click']['behat_editor_example_field_action'] = array(
            '#type' => 'select',
            '#title' => t('And I'),
            '#name' => 'behat_editor_example_field_click_on_type',
            '#description' => t('And I click or press on a link or button or element <b>called</b>'),
            '#options' => array('follow' => t('click'), 'press' => t('press')),
            '#validated' => TRUE,
            '#attributes' => array(
                'class' => array('col-mg-12', 'behat_editor_example_click_group'),
                'data-type' => array('select'),
            ),
        );

        $form['questions_area']['question']['questions']['form_fields_and_elements']['behat_editor_example_click']['behat_editor_example_field_type'] = array(
            '#type' => 'select',
            '#name' => 'behat_editor_example_field_click_on_type',
            '#description' => t('Choose the type eg a css path like div > p:nth-child(1) or name|label|id'),
            '#options' => array(
                            'the element' => t('the element (css path)'),
                            ' ' => t('name|label|id'),
                            'the xpath' => t('the xpath'),
                          ),
            '#validated' => TRUE,
            '#attributes' => array(
                'class' => array('col-mg-12', 'behat_editor_example_click_group'),
                'data-type' => array('select'),
            ),
        );

        $form['questions_area']['question']['questions']['form_fields_and_elements']['behat_editor_example_click']['behat_editor_example_field_text'] = array(
            '#type' => 'textarea',
            '#name' => 'behat_editor_example_field_text',
            '#attributes' => array(
                'class' => array('col-mg-12', 'behat_editor_example_click_group'),
                'data-type' => array('textfield'),
                'placeholder' =>  t('enter the target either an css path or name|label|id'),
            ),
        );

        $form['questions_area']['question']['questions']['form_fields_and_elements']['behat_editor_example_click']['behat_editor_example_action_button'] = array(
            '#type' => 'button',
            '#name' => 'behat_editor_example_action_button',
            '#value' => t('Add'),
            '#attributes' => array(
                'data-method' => array('append'),
                'data-step-group' => array('behat_editor_example_click_group'),
                'class' => array('steps')
            ),
            '#suffix' => '<hr>'
        );

    }
}